apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ppomppu-monitoring-cron
spec:
  schedule: '*/10 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ppomppu-monitoring-cron 
            image: byrnedo/alpine-curl
            imagePullPolicy: IfNotPresent
            command : ["/bin/sh"]
            args:
            - -c
            - curl -X GET -H 'Content-Type:application/json' http://ppomppu-monitoring-service:8001/ppomppu_monitor -d '{"param_list":"ppomppu-anal-service,80,/postanal/?post=,0,Y,KT,Y,ppomppu-monitoring-db,8999,50026600,676003420:AAH7fq_HZzxbmWurz-IWdeUh6vZN1QTQxsE"}'
          restartPolicy: OnFailure
