apiVersion: v1
kind: Service
metadata:
  name: ppomppu-monitoring-service
  labels:
    app: ppomppu-monitoring
  namespace: ppomppu-ns  
spec:
  ports:
  - port: 5003 
    name: http
    targetPort: 5003 
  selector:
    app: ppomppu-monitoring
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ppomppu-monitoring-d1
  namespace: ppomppu-ns
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ppomppu-monitoring
    spec:
      containers:
      - name: ppomppu-monitor
        image: shclub/ppomppu_monitor:latest
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5003 

