version: '3'

services:
  ppomppu_monitor:
    image: shclub/ppomppu_monitor:latest
    ports:
     - "8001:5003"
    depends_on:
     - ppomppu-monitoring-db
     - ppomppu-anal-service 

  ppomppu-monitoring-db:
    image: mongo
    ports:
      - "8999:27017"
    volumes:
      - 'mongodb_data:/test'

  ppomppu-anal-service:
    image: naihil/ppomppu:v2
    ports:
     - "80:8000"

volumes:
  mongodb_data:
    driver: local
