apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: shclubppomppu 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shclubppomppu 
    spec:
      containers:
        - name: shclubppomppu 
          image: jakeleeacr112.azurecr.io/shclubppomppu 
          ports:
          - containerPort: 5003